---
title: "Crow Fault Bars"
author: "Justin Mann"
date: "2024-10-04"
output: html_document
---

```{r libraries}
library(tidyverse)
library(lme4)
library(nnet)
library(broom)
library(glmmTMB)
library(MCMCglmm)
```


```{r import longform data}
fb.df <- read.csv("FaultBarData.csv", h=T)
fb.df$Length <- as.numeric(fb.df$Length)
fb.df$Habitat <- as.factor(fb.df$Habitat)
fb.df <- fb.df %>% drop_na(Grade, Habitat, Length)
fb.df$Grade <- as.factor(fb.df$Grade)
fb.df$Feather <- as.factor(fb.df$Feather)
```


```{r Length Scatter Plot}
range(fb.df$Length)
plot(fb.df$Length)
```

```{r Length Histogram}
hist(fb.df$Length)
```

```{r scaling length}
fb.df$LengthScaled <- scale(fb.df$Length)
```

```{r}
hist(fb.df$LengthScaled)
```


```{r length.mdl}
length.mdl <- lmer(LengthScaled ~  Habitat + (1|Feather), data = fb.df)
summary(length.mdl)
```

```{r residual distribution}
hist(residuals(length.mdl))
```


```{r grade.mdl}
grade.mdl <- nnet::multinom(Grade ~  Habitat, data = fb.df)
summary(grade.mdl)
broom::tidy(grade.mdl)
```


```{r import short form data}
fbs.df <- read.csv("FeatherMaster_1Nov24.csv", h=T)
fbs.df <- fbs.df[,1:15]
fbs.df$ID <- as.factor(fbs.df$ID)
n_occur <- data.frame(table(fbs.df$ID))
n_occur[n_occur$Freq > 1,]#no repeat IDs
```


```{r}
sum(fbs.df$LightBars[fbs.df$Habitat=="urban"]) #200 urban light bars
sum(fbs.df$LightBars[fbs.df$Habitat=="rural"]) #300 rural light bars
```


```{r}
summary(lm(data = fbs.df, LightBars ~ Habitat))
```


```{r}
summary(lm(data = fbs.df, LightBars ~ Habitat))
```

```{r}
light.poisson.mdl <- (glm(data = fbs.df, LightBars ~ Habitat, family = "poisson"))
summary(light.poisson.mdl)
```


```{r zero inflation test}
#zero inflation test from: http://data.princeton.edu/wws509/r/overdispersion.html 
zobs <- fbs.df$LightBars == 0
zpoi <- exp(-exp(predict(light.poisson.mdl)))
c(obs=mean(zobs), poi = mean(zpoi))
```



```{r}
summary(glmmTMB(data = fbs.df, LightBars ~ Habitat, ziformula = ~1, family = "poisson"))
```


```{r}
theme_set(theme_classic())
mean(fbs.df$LightBars[fbs.df$Habitat=="urban"])
mean(fbs.df$LightBars[fbs.df$Habitat=="rural"])

Habitat <- c("Urban", "Rural")
Means <- c(2.27, 3.3)
HabitatMeans <- data.frame(Habitat,Means)

LightBarDensity.plot <- ggplot(fbs.df, aes(x=LightBars, fill = Habitat))+
  geom_density(alpha=0.5)+
  geom_vline(data = HabitatMeans, aes(xintercept = Means, color=Habitat),
             linetype="dashed",
             size = 1,
             show.legend = FALSE)+
  scale_fill_manual(values = c("#D95F02", "#1B9E77"))

LightBarDensity.plot
```



```{r}

sum(fbs.df$MediumBars[fbs.df$Habitat=="urban"])
sum(fbs.df$MediumBars[fbs.df$Habitat=="rural"])

summary(glmmTMB(data = fbs.df, MediumBars ~ Habitat, ziformula=~1, family = "poisson"))
```


```{r}
summary(glmmTMB(data = fbs.df, StrongBars ~ Habitat, family = "poisson"))
```


```{r}
summary(glmmTMB(data = fbs.df, BarsTotal ~ Habitat, ziformula = ~1, family = "poisson"))
```


```{r}
mean(fbs.df$BarsTotal[fbs.df$Habitat=="urban"])
mean(fbs.df$BarsTotal[fbs.df$Habitat=="rural"])

TotHabitat <- c("Urban", "Rural")
TotMeans <- c(3.83, 5.42)
TotHabitatMeans <- data.frame(TotHabitat,TotMeans)

TotalBarDensity.plot <- ggplot(fbs.df, aes(x=BarsTotal, fill = Habitat))+
  geom_density(alpha=0.5)+
  geom_vline(data = HabitatMeans, aes(xintercept = TotMeans, color=TotHabitat),
             linetype="dashed",
             size = 1,
             show.legend = FALSE)+
  scale_fill_manual(values = c("#D95F02", "#1B9E77"))

TotalBarDensity.plot
```

#1. Restrict by feather type
#  - Total fault bars
#  - Medium fault bars

#2. Combine light and medium fault bars

#3. Feather weight by Habitat for feather type

#4. Length of fault bar by Habitat
```{r}
summary(lm(data = fbs.df, DamageScore ~ Habitat))
```


```{r}
summary(lm(data = fbs.df, LightLength ~ Habitat))
```


```{r}
summary(lm(data = fbs.df, MediumLength ~ Habitat))
```


```{r}
summary(lm(data = fbs.df, StrongLength ~ Habitat))
```


```{r}
fbs.prim.df <- subset(fbs.df, Type == "primary")
```


```{r}
summary(lm(data = fbs.prim.df, LightBars ~ Habitat))
```

